### ISSUE TITLE
Support multi-line input (i.e. textarea)

### ISSUE THREAD

**Issue by drzax** [tmcw-up-for-adoption/d3-metatable#10]
Another (possibly more attractive option) would be a div with contenteditable attribute.

**Comment by tmcw** [comment]
This might be a bit tricky to implement, since columns would still want to line up... want to take a shot at implementing it?

**Comment by drzax** [comment]
Sure thing. Already started, will have a branch up soon.

**Comment by drzax** [comment]
Great to see this merged, thanks. Out of curiosity, why the revival of activity here after so long?
